-- require("tokyonight").setup(
--   {
--     -- your configuration comes here
--     -- or leave it empty to use the default settings
--     style = "night", -- The theme comes in three styles, `storm`, `moon`, a darker variant `night` and `day`
--     transparent = true, -- Enable this to disable setting the background color
--     styles = {
--       -- Style to be applied to different syntax groups
--       -- Value is any valid attr-list value for `:help nvim_set_hl`
--       comments = {italic = true},
--       keywords = {italic = true},
--       functions = {},
--       variables = {},
--       -- Background styles. Can be "dark", "transparent" or "normal"
--       sidebars = "transparent", -- style for sidebars, see below
--       floats = "transparent" -- style for floating windows
--     },
--     sidebars = {"qf", "help", "vista_kind", "terminal"}, -- Set a darker background on sidebar-like windows. For example: `["qf", "vista_kind", "terminal", "packer"]`
--     lualine_bold = false, -- When `true`, section headers in the lualine theme will be bold
--     --- You can override specific color groups to use other groups or a hex color
--     --- function will be called with a ColorScheme table
--     ---@param colors ColorScheme
--     on_colors = function(colors)
--     end,
--     --- You can override specific highlights to use other groups or a hex color
--     --- function will be called with a Highlights and ColorScheme table
--     ---@param highlights Highlights
--     ---@param colors ColorScheme
--     on_highlights = function(highlights, colors)
--     end
--   }
-- )

-- trying to make things transparent
-- vim.cmd("au ColorScheme * hi Normal ctermbg=none guibg=none")
-- vim.cmd("au ColorScheme * hi SignColumn ctermbg=none guibg=none")
-- vim.cmd("au ColorScheme * hi NormalNC ctermbg=none guibg=none")
-- vim.cmd("au ColorScheme * hi MsgArea ctermbg=none guibg=none")
-- vim.cmd("au ColorScheme * hi TelescopeBorder ctermbg=none guibg=none")
-- vim.cmd("au ColorScheme * hi NvimTreeNormal ctermbg=none guibg=none")
-- vim.cmd("let &fcs='eob: '")
