require("lsp.nvim_lsp")
-- supported lsps
require("lsp.bashls_lsp")
require("lsp.eslint_lsp")
require("lsp.gopls_lsp")
require("lsp.jsonls_lsp")
require("lsp.lua_lsp")
require("lsp.pyright_lsp")
require("lsp.tsserver_lsp")
require("lsp.yamlls_lsp")
require("lsp.sqlls_lsp")
require("lsp.marksman_lsp")
require("lsp.null_ls")
require("lsp.css")
require("lsp.tailwindcss")
require("lsp.emmet")
require("lsp.html")
