-- this is adding lag. Disable
-- require("lsp_signature").setup(
--   {
--     bind = true,
--     handler_opts = {
--       border = "rounded"
--     },
--     toggle_key = "<M-x>",
--     floating_window = false
--   }
-- )
